# -*- coding: utf-8 -*-
"""
@author:XuMing（xuming624@qq.com)
@description: 
"""

# -*- coding: utf-8 -*-
"""hello_bot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/deepmipt/DeepPavlov/blob/master/docs/intro/hello_bot.ipynb

# Hello bot!

Open in [Colaboratory](https://colab.research.google.com/github/deepmipt/DeepPavlov/blob/master/docs/intro/hello_bot.ipynb)
"""

"""
!pip install -q deeppavlov
Import key components to build HelloBot.
"""

from deeppavlov.agents.default_agent.default_agent import DefaultAgent
from deeppavlov.agents.processors.highest_confidence_selector import HighestConfidenceSelector
from deeppavlov.skills.pattern_matching_skill import PatternMatchingSkill

"""Create skills as pre-defined responses for a user's input containing specific keywords and regular expressions. Every skill returns response and confidence."""

hello = PatternMatchingSkill(responses=['Hello!'], patterns=["hi", "hello", "good day"])
bye = PatternMatchingSkill(['Goodbye!', 'See you around'],
                           patterns=["bye", "chao", "see you"])
fallback = PatternMatchingSkill(["I don't understand, sorry", 'I can say "Hello world!"'])

"""Agent executes skills and then takes response from the skill with the highest confidence."""

agent = DefaultAgent([hello, bye, fallback], skills_selector=HighestConfidenceSelector())

"""Give the floor to the HelloBot!"""

print(agent(['Hello', 'Bye', 'Or not', 'HI', 'see you', 'your name ?']))
