# Generated by Django 3.0.5 on 2020-04-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20)),
                ('ideaid', models.CharField(max_length=20)),
                ('query', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('desc1', models.CharField(max_length=255)),
                ('show_url', models.CharField(max_length=255)),
                ('target_url', models.CharField(max_length=255)),
                ('show_date', models.CharField(max_length=255)),
                ('risk_name', models.CharField(max_length=255)),
                ('risk_word', models.CharField(max_length=255)),
            ],
        ),
    ]
